---
Name: myproject
---
# SilverStripe\SiteConfig\SiteConfig:
#   extensions:
#     - SiteConfigExtension
# Page:
#   extensions:
#     - OpenGraphExtension
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SilverStripe\View\SSViewer:
  themes:
    - '$public'
    - 'bootstrap'
    - '$default'
SilverStripe\Assets\InterventionBackend:
  flush_enabled: false
